/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Simple sharing status response
 * @export
 * @interface BotSharingStatusResponse
 */
export interface BotSharingStatusResponse {
    /**
     * Whether published to marketplace
     * @type {boolean}
     * @memberof BotSharingStatusResponse
     */
    'is_published': boolean;
    /**
     * List of department IDs where the bot is published
     * @type {Array<string>}
     * @memberof BotSharingStatusResponse
     */
    'group_ids'?: Array<string>;
    /**
     * Whether the bot is published globally
     * @type {boolean}
     * @memberof BotSharingStatusResponse
     */
    'is_global'?: boolean;
}

