/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BotPublishRequest
 */
export interface BotPublishRequest {
    /**
     * List of department IDs to publish to, or [\"*\"] for global publishing
     * @type {Array<string>}
     * @memberof BotPublishRequest
     */
    'group_ids': Array<string>;
}

