/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Collection sharing status response
 * @export
 * @interface CollectionSharingStatusResponse
 */
export interface CollectionSharingStatusResponse {
    /**
     * Whether published to marketplace
     * @type {boolean}
     * @memberof CollectionSharingStatusResponse
     */
    'is_published': boolean;
    /**
     * List of department IDs where the collection is published
     * @type {Array<string>}
     * @memberof CollectionSharingStatusResponse
     */
    'group_ids'?: Array<string>;
    /**
     * Whether the collection is published globally
     * @type {boolean}
     * @memberof CollectionSharingStatusResponse
     */
    'is_global'?: boolean;
}

