/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Department } from './department';
// May contain unused imports in some cases
// @ts-ignore
import type { PageResult } from './page-result';

/**
 * A list of departments
 * @export
 * @interface DepartmentList
 */
export interface DepartmentList {
    /**
     * 
     * @type {Array<Department>}
     * @memberof DepartmentList
     */
    'items'?: Array<Department>;
    /**
     * 
     * @type {PageResult}
     * @memberof DepartmentList
     */
    'pageResult'?: PageResult;
}

