/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Department
 */
export interface Department {
    /**
     * The ID of the department
     * @type {string}
     * @memberof Department
     */
    'id'?: string;
    /**
     * The parent department ID, -1 for root department
     * @type {string}
     * @memberof Department
     */
    'parent_id'?: string;
    /**
     * The name of the department
     * @type {string}
     * @memberof Department
     */
    'name'?: string;
    /**
     * The status of the department (0=inactive, 1=active)
     * @type {number}
     * @memberof Department
     */
    'status'?: DepartmentStatusEnum;
    /**
     * The hierarchical path of the department
     * @type {string}
     * @memberof Department
     */
    'group_path'?: string;
    /**
     * The tenant ID this department belongs to
     * @type {string}
     * @memberof Department
     */
    'tenant_id'?: string;
    /**
     * The date and time the department was created
     * @type {string}
     * @memberof Department
     */
    'created_at'?: string;
    /**
     * The date and time the department was last updated
     * @type {string}
     * @memberof Department
     */
    'updated_at'?: string;
    /**
     * Child departments (only present in hierarchical mode)
     * @type {Array<Department>}
     * @memberof Department
     */
    'children'?: Array<Department>;
}

export const DepartmentStatusEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;

export type DepartmentStatusEnum = typeof DepartmentStatusEnum[keyof typeof DepartmentStatusEnum];


