/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SharedBotConfig } from './shared-bot-config';

/**
 * Shared bot information for marketplace users
 * @export
 * @interface SharedBot
 */
export interface SharedBot {
    /**
     * Bot ID
     * @type {string}
     * @memberof SharedBot
     */
    'id': string;
    /**
     * Bot title
     * @type {string}
     * @memberof SharedBot
     */
    'title': string;
    /**
     * Bot description
     * @type {string}
     * @memberof SharedBot
     */
    'description'?: string;
    /**
     * Bot type
     * @type {string}
     * @memberof SharedBot
     */
    'type': SharedBotTypeEnum;
    /**
     * Original owner user ID
     * @type {string}
     * @memberof SharedBot
     */
    'owner_user_id': string;
    /**
     * Original owner username
     * @type {string}
     * @memberof SharedBot
     */
    'owner_username'?: string;
    /**
     * Subscription record ID (has value if subscribed, null if not subscribed)
     * @type {string}
     * @memberof SharedBot
     */
    'subscription_id'?: string;
    /**
     * Subscription time (only has value when subscribed)
     * @type {string}
     * @memberof SharedBot
     */
    'gmt_subscribed'?: string;
    /**
     * Bot configuration settings (read-only)
     * @type {SharedBotConfig}
     * @memberof SharedBot
     */
    'config': SharedBotConfig;
    /**
     * Whether current user has subscribed to this bot
     * @type {boolean}
     * @memberof SharedBot
     */
    'is_subscribed': boolean;
    /**
     * Whether current user is the owner of this bot
     * @type {boolean}
     * @memberof SharedBot
     */
    'is_owner': boolean;
}

export const SharedBotTypeEnum = {
    knowledge: 'knowledge',
    common: 'common',
    agent: 'agent'
} as const;

export type SharedBotTypeEnum = typeof SharedBotTypeEnum[keyof typeof SharedBotTypeEnum];


