/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SharedBot } from './shared-bot';

/**
 * Shared bot list response
 * @export
 * @interface SharedBotList
 */
export interface SharedBotList {
    /**
     * List of shared bots
     * @type {Array<SharedBot>}
     * @memberof SharedBotList
     */
    'items': Array<SharedBot>;
    /**
     * Total count (for pagination)
     * @type {number}
     * @memberof SharedBotList
     */
    'total': number;
    /**
     * Current page number
     * @type {number}
     * @memberof SharedBotList
     */
    'page': number;
    /**
     * Page size
     * @type {number}
     * @memberof SharedBotList
     */
    'page_size': number;
}

