/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelSpec } from './model-spec';
// May contain unused imports in some cases
// @ts-ignore
import type { SharedCollection } from './shared-collection';

/**
 * 
 * @export
 * @interface SharedBotConfigAgent
 */
export interface SharedBotConfigAgent {
    /**
     * 
     * @type {ModelSpec}
     * @memberof SharedBotConfigAgent
     */
    'completion'?: ModelSpec;
    /**
     * 
     * @type {string}
     * @memberof SharedBotConfigAgent
     */
    'system_prompt_template'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedBotConfigAgent
     */
    'query_prompt_template'?: string;
    /**
     * 
     * @type {Array<SharedCollection>}
     * @memberof SharedBotConfigAgent
     */
    'collections'?: Array<SharedCollection>;
}

