/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SharedBotConfigAgent } from './shared-bot-config-agent';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowDefinition } from './workflow-definition';

/**
 * Configuration settings for shared bot (read-only version)
 * @export
 * @interface SharedBotConfig
 */
export interface SharedBotConfig {
    /**
     * 
     * @type {SharedBotConfigAgent}
     * @memberof SharedBotConfig
     */
    'agent'?: SharedBotConfigAgent;
    /**
     * 
     * @type {WorkflowDefinition}
     * @memberof SharedBotConfig
     */
    'flow'?: WorkflowDefinition;
}

