"""empty message

Revision ID: 3b1ed569b24b
Revises: d112e0332219
Create Date: 2025-09-24 14:13:46.343939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b1ed569b24b'
down_revision: Union[str, None] = 'd112e0332219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_marketplace',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('bot_id', sa.String(length=24), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gmt_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gmt_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bot_marketplace_bot_group', 'bot_marketplace', ['bot_id', 'group_id'], unique=False)
    op.create_index('idx_bot_marketplace_bot_id', 'bot_marketplace', ['bot_id'], unique=False)
    op.create_index('idx_bot_marketplace_gmt_deleted', 'bot_marketplace', ['gmt_deleted'], unique=False)
    op.create_index('idx_bot_marketplace_group_id', 'bot_marketplace', ['group_id'], unique=False)
    op.create_index('idx_bot_marketplace_list', 'bot_marketplace', ['status', 'gmt_created'], unique=False)
    op.create_index('idx_bot_marketplace_status', 'bot_marketplace', ['status'], unique=False)
    op.create_index(op.f('ix_bot_marketplace_gmt_deleted'), 'bot_marketplace', ['gmt_deleted'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('group_path', sa.String(length=1024), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_department_parent_id', 'department', ['parent_id'], unique=False)
    op.create_index('ix_department_tenant_id', 'department', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_department_tenant_id', table_name='department')
    op.drop_index('ix_department_parent_id', table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_bot_marketplace_gmt_deleted'), table_name='bot_marketplace')
    op.drop_index('idx_bot_marketplace_status', table_name='bot_marketplace')
    op.drop_index('idx_bot_marketplace_list', table_name='bot_marketplace')
    op.drop_index('idx_bot_marketplace_group_id', table_name='bot_marketplace')
    op.drop_index('idx_bot_marketplace_gmt_deleted', table_name='bot_marketplace')
    op.drop_index('idx_bot_marketplace_bot_id', table_name='bot_marketplace')
    op.drop_index('idx_bot_marketplace_bot_group', table_name='bot_marketplace')
    op.drop_table('bot_marketplace')
    # ### end Alembic commands ###
