"""empty message

Revision ID: 115b2a93f311
Revises: 3b1ed569b24b
Create Date: 2025-09-25 15:39:22.961058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115b2a93f311'
down_revision: Union[str, None] = '3b1ed569b24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('tenant_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'tenant_name')
    # ### end Alembic commands ###
