"""empty message

Revision ID: 65bdc048d554
Revises: 115b2a93f311
Create Date: 2025-09-26 15:00:48.825130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bdc048d554'
down_revision: Union[str, None] = '115b2a93f311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_marketplace', sa.Column('group_id', sa.String(length=64), nullable=True))
    op.drop_constraint(op.f('uq_collection_marketplace_collection'), 'collection_marketplace', type_='unique')
    op.create_index('idx_collection_marketplace_collection_group', 'collection_marketplace', ['collection_id', 'group_id'], unique=False)
    op.create_index('idx_collection_marketplace_group_id', 'collection_marketplace', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_collection_marketplace_group_id', table_name='collection_marketplace')
    op.drop_index('idx_collection_marketplace_collection_group', table_name='collection_marketplace')
    op.create_unique_constraint(op.f('uq_collection_marketplace_collection'), 'collection_marketplace', ['collection_id'])
    op.drop_column('collection_marketplace', 'group_id')
    # ### end Alembic commands ###
